version: '3.8'
services:
  db:
    image: postgres:14.15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather-app
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/docker/volumes/postgres_data/

#volumes:
#  postgres_data: